Repository googleapis/nodejs-local-auth, pull requests merged in 2020-06, with the labels that each got.

#10 feat(secrets): begin migration to secret manager from keystore
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, context: full

#12 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#13 chore: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#14 build: add .gitattributes config
  .gitattributes
Labels: cla: yes

#15 build: add config .gitattributes
  .gitattributes
  .kokoro/.gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
